--- 
abstract: Run Web::Scraper From Config Files
author: Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Web-Scraper-Config
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::Any: 0
  Data::Visitor::Callback: 0
  URI: 0
  Web::Scraper: 0
version: 0.01
